### ISSUE TITLE
after update: shorcodes didn't work

### ISSUE THREAD

**Issue by ErkkiTuomiLMSaatchi** [linchpin/mesh#168]
Hi,

After the update 1.2 mesh sections don't seem to accept data-attributes. Shortcode renders but strips all data-attributes away leaving html as is.

So, lets say we have this kind of shortcode:
```
function otayhteys_shortcode( $atts, $content = null ) {
	return '<a class="float-left" data-open="exampleModal1">' . $content . '</a>';
}
add_shortcode( 'otayhteys', 'otayhteys_shortcode' );
```
which renders like this

`<a class="float-left"> content </a>`

greets,

Eki

**Comment by aaronware** [comment]
@ErkkiTuomiLMSaatchi in order to use a custom `data-open` attribute you should utilize the following `mesh_allowed_html` filter. https://meshplugin.com/knowledgebase/mesh_allowed_html/ this has actually been in place since 1.1. Did you potentially edit the plugin to allow your custom data attribute previously?
