### ISSUE TITLE
Mesh 1.2.3 and wordpress 4.9.4 add sections to templates not available

### ISSUE THREAD

**Issue by boiciuc** [linchpin/mesh#191]
I have a clean install of Wordpress 4.9.4 and Mesh 1.2.3. When i try to create a Mesh Template i don`t have any option to add sections to it. Am I missing something ?

![mesh_templates_error](https://user-images.githubusercontent.com/6917578/37211497-c8b5c9fa-23b4-11e8-832d-0ee37da429ef.png)

**Comment by aaronware** [comment]
I can take a look at this for you. It should work out of the box on 4.9.X

**Comment by aaronware** [comment]
Hi @boiciuc I have tried numerous times to replicated this and have not been able to. Is there anything being displayed within your log file for this? I know it's been quite some times that you posted this but if you have any information let me know

**Comment by aaronware** [comment]
I think I was able to figure out WHY it was happening but wasn't able to actually get it to happen a natural way.

I think this happened because the mesh_template post type was some how removed from the initial settings (or wasn't configured properly by the plugin). I've made it so any time the post types area is updated it will validate to make sure mesh_templates always allow mesh_sections.

**Comment by aaronware** [comment]
Rolled out in 1.2.4
