### ISSUE TITLE
Ability to add width related classes to columns to override defaults

### ISSUE THREAD

**Issue by alandowling** [linchpin/mesh#210]
For example, for 2 columns the default classes are small-12 and medium-6 but the user might want the classes small-6/small-6 and medium-4/medium-8 respectively. 

Goal should be that adding the custom classes would override the defaults.

Related to https://github.com/linchpin/mesh/issues/143

**Comment by sitesandsuch** [comment]
I do this by adding classes to the CSS. Example:
`.large-4-override { 
@include flex-grid-column(4); @include breakpoint(small only) { max-width: 100%; flex: 0 0 100%; }
                                                   @include breakpoint(medium only) { max-width: 100%; flex: 0 0 50%; }}`

Add 'large-4-override' to each of two columns in a row and each will 33% wide on large and up, 50% on medium and 100% on small.

**Comment by aaronware** [comment]
In order to get this request to change out small css class I'm going to create a filter for this. The filter will pass the default class as well as the post id (which is the section/block id). So you can target it individually if you need to. It'll at least allow you to override it.

The medium sizing can be done by resizing the columns so I dunno if you need to change the default. Additionally you could also create a Mesh Template if you find that you are always making each section an 8/4 and don't want to drag the slider.

For the longer term it probably needs a UI. I have some ideas on it but due to all the additional layers of settings and saving of post meta I punted it.

**Comment by aaronware** [comment]
1st Q : Regarding `large-7 .large-centered` classes, I believe you could just add those CSS classes to the single block level yes/no?

![Column/Block level CSS Class field](https://cldup.com/hcSZ9z7OJc.png)

1st Q: Part 2. Take a look at release/1.2.5 as I added in single column centering!
`.medium-9 .medium-centered` would be handled in the UI

![Single Column/Block Centering](https://cldup.com/QLnCkA5uvo.png)

2nd Q: If you are merely adding in larger sizes you can simply add `large-5` and `large-7` to their respective block/column level css classes. It's kind of a pain because you'd need to adjust them manually. Similar to Q 1

What I would suggesting is use `mesh_column_classes` filter and str_replace the small-12 and then just add in your small classes in the CSS Class area of the UI. It's the quickest work around while the UI for controlling column sizes for all screen sizes.

I started prototyping a nested tab navigation that would be needed to control what "size" you are looking at but I need to change the data structure to accomodate which is a bit of an undertaking

**Comment by aaronware** [comment]
1.2.5 will introduce passing the Post ID of the block you are adjusting, you can then target individual blocks if you want to.

**Comment by aaronware** [comment]
Just wanted to circle back that this filter `mesh_column_classes` now passes the current $post_id for the block. You can check against that to target specific classes OR you can just simply update all classes as needed.

As I mentioned before, I have some plans for some size specific css classes but still need to get the prototype in a better spot before I tackle it.

**Comment by sitesandsuch** [comment]
Hi Aaron,

Downloaded 1.2.5.1 and working with it. $post_id works great.

There is a problem with the bg images: 

On a clean install, insert a mesh section. Set bg image on the outer section. This is fine. Now set a bg image for a cell (1 or 2 column). On return from Media Library, this new image will replace the first bg image set.

Regards,

Michiel

**Comment by aaronware** [comment]
@sitesandsuch 1.2.5.2 is going to be released today (barring any issues that come up in testing) and it should resolve the Column BG image issue you were seeing

**Comment by aaronware** [comment]
This is all set.
