### ISSUE TITLE
Use Flexbox or XY-grid as an option

### ISSUE THREAD

**Issue by sitesandsuch** [linchpin/mesh#214]
Foundation 6.4.0 introduced the XY-grid. I would like to use this in my projects with Mesh (Mesh = AWESOME) so started to amend current 1.2.4 release so it is available as an option. I have made a PR that has initial work done for a first review. Used 1.2.4 as current develop branch has some interesting features I don't all fully understand. Changes are easy to merge into any branch. Anyway, just a start. I will be using this in new project starting this week, and will tweak code as I go along.

**Comment by aaronware** [comment]
@sitesandsuch I took a look at your pull request and I like the overall idea. I think what you are trying to accomplish can be done with a new filter being added within the grid-systems along with the idea that @maxinacube has regarding #190. This would substantially cut down on code complexity/maintainability.

I'm not sure there was a need to override the string 'columns' everywhere in the plugin as many of those variable names are not directly tied to the CSS class usage you are looking to override

**Comment by aaronware** [comment]
Actually after reviewing some of the templates, Mesh can _almost_ do what you need. I can make a few alterations and show you what I mean in a demo. I definitely want to get the flex grids in there as default options along with implementing some filters

**Comment by strarsis** [comment]
Would using the [CSS grid module](https://caniuse.com/#feat=css-grid) offer even more simplicity?

**Comment by sitesandsuch** [comment]
@aaronware Awesome. Looking forward to it. Let me know if I can do something.

**Comment by aaronware** [comment]
Hey @sitesandsuch Take a look at release 1.2.5 when you get a second. I just merged in https://github.com/linchpin/mesh/pull/219 which takes your overarching idea and makes it a bit more extendible in the future.

I made it so Mesh can support Float, Flex and XY grids, including the ability to filter what classes are used for columns and rows. So rather than hardcoding the class names now we have a bit more option to change it out in the future if some one chooses or when Zurb/Foundation comes up with the next big thing.

I'd love to get your feedback as you gave the shove to get it going.

Also keep in mind 1.2.5 has a lot of other features going on as well so adding more support for grid systems is just one part of the release.

@strarsis you could technically use the CSS Grid Layout today in the current version of Mesh because it's agnostic to what CSS classes are used. With this release though you could more easily define what classes are used for the grid defined in the css. I haven't looked too much into XY grid but I assume it is probably based on the CSS Grid layout

**Comment by sitesandsuch** [comment]
VERY NICE! Works out of the box with xy-classes. Yes, xy-grid is based on CSS Grid layout. The Push Pull option can be hidden/removed as source ordering takes care of this ("small-order-2 medium-order-1"). Equalizer can also be removed, as flexbox children are of identical height by default.
