### ISSUE TITLE
Sections not showing in "Default" template in Wordpress...

### ISSUE THREAD

**Issue by ux-cro** [linchpin/mesh#88]
Hi There,

I've installed Mesh and have added content in the back-end; however, when I publish the page and look at the live site, the sections are not appearing when the Wordpress page uses the default template.

When using another template (Contact Template), the sections appear. 

Can anyone explain how to get the sections showing in the default template, please?

Many thanks.

**Comment by aaronware** [comment]
Hey @ux-cro sorry for the delay here.

The mesh sections typically pull into "the content" by default within a page / single post. If you are using the default home page in order to pull in the blog archive. I don't think I've ever used it in that context. It's possible to do but you would have to adjust a template to make it work that way.

This might be a feature request.

Typical use case though is on "single" versions of a given post type and not on the archive.
